fetch('url').then((res) => {
    return;
}).then((res) => {
    return;
}).catch((err) => {
    console.log(`Something bad happend: ${err}`);
})